#!/bin/bash

center_text() {
    COLUMNS=$(tput cols)
    printf "%*s\n" $(((${#1}+$COLUMNS)/2)) "$1"
}

display_file_center() {
    columns=$(tput cols)
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}

green=`tput setaf 2`
magenta=`tput setaf 5`
white=`tput setaf 7`
blue=`tput setaf 4`
reset=`tput sgr0`

clear
echo && echo
toilet -F metal -f sblood -w 100 "    Updates"
echo && echo
echo "${green} "
center_text ":: Retrieving package update list ::"
echo "${magenta} "

checkupdates > /tmp/updtemp.tmp

if [ `ls -l /tmp/updtemp.tmp | awk '{print $5}'` -eq 0 ]; then
	center_text "No Updates Available :("
		else
	display_file_center "/tmp/updtemp.tmp"
fi

#center_text $upd
echo "${green} "
center_text ":: Retreiving devel update list ::"
echo "${reset} "
pacaur --check --devel > /tmp/gittemp.tmp
sed -i -e 's/^/     /' /tmp/gittemp.tmp
cat "/tmp/gittemp.tmp"
echo && echo
echo "${white} "
center_text "Press [Enter]"
echo "${reset} "
read -p " "
rm /tmp/updtemp.tmp
exit


