#!/usr/bin/env bash

vertical="/home/tmplt/media/wallpapers/vertical/"
horizontal="/home/tmplt/media/wallpapers/"

function randomwp() {
    find "$1" -maxdepth 1 -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z
}

while true; do
    feh --bg-fill "$(randomwp $horizontal)" \
        --bg-fill "$(randomwp $vertical)" \
        --bg-fill "$(randomwp $vertical)" \
        >/dev/null 2>/dev/null
    sleep 45m
done

